/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "acsuser_constants.h"



const acsuserConstants g_acsuser_constants;

acsuserConstants::acsuserConstants() {
}



